#pragma once

#define CHERT_MOUSE_BUTTON_1         0
#define CHERT_MOUSE_BUTTON_2         1
#define CHERT_MOUSE_BUTTON_3         2
#define CHERT_MOUSE_BUTTON_4         3
#define CHERT_MOUSE_BUTTON_5         4
#define CHERT_MOUSE_BUTTON_6         5
#define CHERT_MOUSE_BUTTON_7         6
#define CHERT_MOUSE_BUTTON_8         7
#define CHERT_MOUSE_BUTTON_LAST      CHERT_MOUSE_BUTTON_8
#define CHERT_MOUSE_BUTTON_LEFT      CHERT_MOUSE_BUTTON_1
#define CHERT_MOUSE_BUTTON_RIGHT     CHERT_MOUSE_BUTTON_2
#define CHERT_MOUSE_BUTTON_MIDDLE    CHERT_MOUSE_BUTTON_3